b/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    url(r'^', include('birds.urls'), name='birds'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('^accounts/', include('django.contrib.auth.urls')),
]

birds/urls.py
from django.conf.urls import url

from . import views

app_name = 'birds'
urlpatterns = [
	url(r'^$', views.index_view, name='index'),
	url(r'^authuser/', views.authenticate_user, name='authuser'),
	url(r'^setusername/', views.setusername, name='setusername'),
	url(r'^signs3/', views.signs3, name='signs3'),
	url(r'^user/(?P<pk>[-\w]+)/$', views.user, name='user'),
	url(r'^add_avatar/', views.add_avatar, name='add_avatar'),
	url(r'^about/', views.about, name='about'),
	url(r'^privacy_policy/', views.privacy_policy, name='privacy_policy'),
	url(r'^terms_of_service/', views.terms_of_service, name='terms_of_service'),
	url(r'^new_sighting/', views.new_sighting, name='new_sighting'),
	url(r'^edit_sighting/(?P<pk>[-\w]+)/$', views.edit_sighting, name='edit_sighting'),
	url(r'^view_sighting/(?P<pk>[-\w]+)/$', views.view_sighting, name='view_sighting'),
	#url(r'^weather/', views.weather, name="weather"),
	url(r'^species_query/', views.species_query, name='species_query'),
	url(r'^new_comment/', views.new_comment, name='new_comment'),
	url(r'^get_comments/', views.get_comments, name='get_comments'),
	url(r'^get_new_notifications_for_user/', views.get_new_notifications_for_user, name='get_new_notifications_for_user'),
	url(r'^like/', views.like, name='like'),
	url(r'^unlike/', views.unlike, name='unlike'),
	url(r'^up_vote_species/', views.up_vote_species, name='up_vote_species'),
	url(r'^down_vote_species/', views.down_vote_species, name='down_vote_species'),
	url(r'^suggest_new_species/', views.suggest_new_species, name='suggest_new_species'),
	url(r'^get_species_suggestions/', views.get_species_suggestions, name='get_species_suggestions'),
	url(r'^remove_photo/', views.remove_photo, name='remove_photo'),
	url(r'^image_inspect/', views.image_inspect, name='image_inspect'),
	url(r'^star_photo/', views.star_photo, name='star_photo'),
	url(r'^accept_species_suggestion/', views.accept_species_suggestion, name="accept_species_suggestion"),
	url(r'^feedback/', views.feedback, name="feedback"),
	url(r'^map/', views.map_view, name="map"),
	url(r'^info_window/', views.info_window, name="info_window"),
	url(r'^get_map_points/', views.get_map_points, name="get_map_points"),
	url(r'^sightings_search', views.sightings_search, name="sightings_search"),
	url(r'^update_search', views.update_search_session, name="update_search"),
	url(r'^.well-known/acme-challenge/UkhVC-nEsTpRuv1r9DcGYM1gVR1Ew9BNqedHbc52Pak', views.certcode, name="certcode"),
	url(r'^robots\.txt$', views.robots, name="robots"),
	url(r'^nothanks', views.nothanks, name="nothanks")
]

birds/forms.py
from django import forms
from .models import Sighting

class SightingsForm(forms.ModelForm):
    class Meta:
        model = Sighting
        fields = ('caption','species_tag','lat','lng','sighting_date', 'location', 'post_text')
        widgets = {
            'caption': forms.TextInput(attrs={'class':"mdl-textfield__input"}),
            'sighting_date': forms.TextInput(attrs={'class':"mdl-textfield__input"}),
            #'species_tag': forms.TextInput(attrs={'class':"mdl-textfield__input"}),
            'sighting_date': forms.TextInput(attrs={'class':"mdl-textfield__input"}),
            'location': forms.TextInput(attrs={'class':"mdl-textfield__input"}),
            'lat': forms.HiddenInput(),
            'lng': forms.HiddenInput(),
            'location': forms.HiddenInput(),
            'post_text': forms.Textarea(attrs={'class':"mdl-textfield__input", 'id':"post_text_textarea"})
        }

birds/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.template.loader import render_to_string
from django.utils import timezone
from .models import *
from django.http import HttpResponse, HttpResponseForbidden
import json
from django.db.models import Q, IntegerField, Value
from django.contrib.auth.models import User
import os
import boto3
import datetime
from django.core import serializers

from .forms import SightingsForm

from django.contrib.auth.decorators import login_required

def about(request):
	request.session['nothanks'] = 1
	return render(request, 'birds/about.html')

def privacy_policy(request):
	return render(request, 'birds/privacy_policy.html')

def terms_of_service(request):
	return render(request, 'birds/terms_of_service.html')

def user(request, pk):
	this_user = get_object_or_404(User, pk=pk)
	sighting_count = Sighting.objects.exclude(sighting_date__isnull=True).filter(user = this_user).count()
	species_count = Sighting.objects.exclude(species_tag__isnull=True).filter(user = this_user).count()
	species_count_ytd = Sighting.objects.filter(sighting_date__year=datetime.datetime.now().year, user = this_user).exclude(species_tag__isnull=True).count()
	helper_species_count = SpeciesSuggestions.objects.filter( user=this_user, accepted=True).count()
	user_stats = {
		"sighting_count":sighting_count,
		"species_count":species_count,
		"species_count_ytd":species_count_ytd,
		"helper_species_count":helper_species_count
	}
	preview_images = BirdPhoto.objects.filter( sighting__user = this_user ).order_by('-sighting__post_ts')
	preview_url = ""
	if preview_images.count() > 0:
		preview_url = preview_images[0].thumbnail_url
	
	return render(request, 'birds/user.html', {"this_user": this_user, "user_stats": user_stats, "preview_url": preview_url })

def signs3(request):
	if request.is_ajax():
		S3_BUCKET = os.environ.get('AWS_STORAGE_BUCKET_NAME')
	
		file_type = "image/jpg"
		
		new_photo = BirdPhoto.objects.create( sighting_id = request.POST.get('sighting_id'), order = 0 )
		filename = "%s.%s" % ( new_photo.id, "jpg" )
		new_photo.photo = filename
		new_photo.thumbnail_url = "https://s3.amazonaws.com/birdingappsmall/%s" % ( filename )
		new_photo.medium_url = "https://s3.amazonaws.com/birdingappmedium/%s" % ( filename )
		new_photo.save()

		s3 = boto3.client('s3')
	
		presigned_post = s3.generate_presigned_post(
			Bucket = S3_BUCKET,
			Key = filename,
			Fields = {"acl": "public-read", "Content-Type": file_type},
			Conditions = [
			 	{"acl": "public-read"},
			 	{"Content-Type": file_type}
			],
			ExpiresIn = 3600
		)
		return HttpResponse(json.dumps({'data': presigned_post,'filename': filename, 'url': new_photo.photo.url, 'id': new_photo.id, 'thumbnail_url': new_photo.thumbnail_url}), content_type='application/json')
	else:
		return HttpResponseForbidden()

@login_required
def setusername(request):
	if request.method == "POST":
		new_username = request.POST.get("username")
		next_url = request.POST.get("next")
		if User.objects.exclude(pk=request.user.pk).filter(username=new_username).exists():
			return render(request, 'birds/setusername.html', { 'error': 'username already exists, please choose another', 'next': next_url })
		else:
			request.user.username = new_username
			request.user.save()
			if next_url:
				return redirect(next_url)
			else:
				return redirect('/user/'+str(request.user.pk), pk=request.user.pk)
	elif request.method == "GET":
		next_url = request.GET.get("next")
		if not next_url:
			return render(request, 'birds/setusername.html')
		else:
			return render(request, 'birds/setusername.html',  { 'next': next_url } )
	else:
		return HttpResponseForbidden()

def authenticate_user(request):
	if request.is_ajax():
		import urllib
		from jose import jwt
		from django.contrib.auth import login
		idtoken = request.POST.get('idtoken')
		target_audience = "the-birding-book"
		certificate_url = 'https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com'
		response = urllib.urlopen(certificate_url)
		certs = response.read()
		certs = json.loads(certs)
		firebase_user = jwt.decode(idtoken, certs, algorithms='RS256', audience=target_audience)
		if User.objects.filter(uid__uid=firebase_user['sub']).exists():
			user = User.objects.get(uid__uid=firebase_user['sub'])
			user.backend = 'django.contrib.auth.backends.ModelBackend'
			login(request, user)
			return HttpResponse(json.dumps({'msg':'old_user'}), content_type='application/json')
		else:
			user = User()
			user.save()
			user.username = 'new_user'+str(user.id)
			user.save()
			
			new_avatar = Avatar.objects.create( user = user )
			filename = 'default_avatar.png'
			new_avatar.avatar = 'default_avatar.png'
			new_avatar.thumbnail_url = "https://s3.amazonaws.com/birdingappsmall/%s" % filename
			new_avatar.save()
			
			uid = Uid.objects.create( uid = firebase_user['sub'], user = user )
			user.backend = 'django.contrib.auth.backends.ModelBackend'
			login(request, user)
			return HttpResponse(json.dumps({'msg':'new_user'}), content_type='application/json')
	else:
		return HttpResponseForbidden()
		
@login_required
def new_sighting(request):
	sightings = Sighting.objects.filter(user_id = request.user.id, sighting_date = None)
	if sightings.count() > 0:
		new_sighting = sightings[0]
		new_sighting.post_ts = timezone.now()
		new_sighting.save()
	else:
		new_sighting = Sighting.objects.create(user_id = request.user.id)
	return redirect('/edit_sighting/'+str(new_sighting.id), pk=new_sighting.id)
# 	return render(request, 'birds/edit_sighting.html', {'form': form, 'this_sighting': edit_sighting})
	

@login_required
def edit_sighting(request, pk):
	this_sighting = get_object_or_404(Sighting, pk=pk)
	form = SightingsForm( request.POST or None, request.FILES or None, instance=this_sighting )
	if request.method == "POST":
		if this_sighting.user_id != request.user.id:
			return HttpResponseForbidden()
		if form.is_valid():
			form.save()
			return redirect('/view_sighting/'+str(pk), pk=pk)
		else:
			return render(request, 'birds/edit_sighting.html', { 'form': form, 'this_sighting': this_sighting })
	elif request.method == "GET":
		return render(request, 'birds/edit_sighting.html', { 'form': form, 'this_sighting': this_sighting })
	else:
		return HttpResponseForbidden()

def view_sighting(request, pk):
	this_sighting = get_object_or_404(Sighting, pk=pk)
	species_votes = SpeciesVote.objects.filter( sighting = this_sighting, species = this_sighting.species_tag ).count()
	if request.user.is_authenticated():
		Notifications.objects.filter( sighting = this_sighting, user_id = request.user.id ).all().update(quiet = True)
		is_liked = Like.objects.filter( user = request.user, sighting = this_sighting ).count()
		is_voted = SpeciesVote.objects.filter( user = request.user, sighting = this_sighting, species = this_sighting.species_tag ).count()	
		return render(request, 'birds/view_sighting.html', { 'sighting': this_sighting, 'is_liked': is_liked, 'is_voted': is_voted,'species_votes': species_votes})
	else:
		return render(request, 'birds/view_sighting.html', { 'sighting': this_sighting, 'species_votes': species_votes})

def index_view(request):
	if request.method == 'GET':
		#latest_sighting_list = Sighting.objects.filter(sighting_date__lte=timezone.now()).order_by('-post_ts')[:10]
		pre_url = BirdPhoto.objects.latest('sighting__post_ts').thumbnail_url
		return render(request, 'birds/index.html', {'preview_url':pre_url})
	else:
		return HttpResponseForbidden()
		
def species_query(request):
	if request.method == "GET":
		term = request.GET.get('term')
		
		if term:
			terms = term.split(' ')
			s_query = Subspecies.objects.filter(  )
			l = list(Subspecies.objects.filter( Q(species__species__icontains=term) | Q(species__species_english__icontains=term) ).exclude(subspecies__isnull=True).order_by('subspecies')[:100])
			l2 = [{'value':unicode(i), 'id':i.pk} for i in l]
			data = json.dumps(l2)
		else:
			data = []
		return HttpResponse(data, content_type='application/json')
	else:
		return HttpResponseForbidden()

def get_comments(request):
	if request.is_ajax():
		comments = Comment.objects.filter( sighting = request.POST.get('this_sighting') ).order_by('post_ts')
		return render_to_response('birds/comments.html', {'comments': comments})
	else:
		return HttpResponseForbidden()

@login_required
def get_new_notifications_for_user(request):
	if request.is_ajax():
		notifications = Notifications.objects.filter( user = request.user, quiet = False ).order_by('-not_ts')
		return render_to_response('birds/user_notifications.html', {'notifications': notifications})
	else:
		return HttpResponseForbidden()
		

@login_required
def new_comment(request):
	if request.is_ajax():
		new_comment = Comment.objects.create( comment = request.POST.get('new_comment'), sighting_id = request.POST.get('sighting_id'), user_id = request.user.id )
		
		if request.user != new_comment.sighting.user:
			notification_message = str(request.user)+": "+request.POST.get('new_comment')[:100]
			Notifications.objects.create( user = new_comment.sighting.user, sighting_id = request.POST.get('sighting_id'), caption = "Comment", msg = notification_message)
		
		user_replies = Comment.objects.filter( sighting_id = request.POST.get('sighting_id') ).exclude(user = new_comment.sighting.user).exclude(user = request.user).values('user').distinct()
		print user_replies
		for reply in user_replies:
			notification_message = str(request.user)+": "+request.POST.get('new_comment')[:100]
			Notifications.objects.create( user_id = reply['user'], sighting_id = request.POST.get('sighting_id'), caption = "Reply", msg = notification_message)
		
		return HttpResponse(json.dumps({'msg':'success'}), content_type='application/json')
	else:
		return HttpResponseForbidden()
	
@login_required 
def like(request):
	if request.is_ajax():
		if Like.objects.filter( user = request.user, sighting_id = request.POST.get('sighting_id') ).count() > 0:

birds/templates/birds/about.html
{% extends 'birds/base.html' %}
{% load staticfiles %}

{% block desc_title %}
<title>The Birding Book - About</title>
<meta name="description" content="Learn about The Birding Book by reviewing the FAQ, privacy policy, and terms of service.">

<meta property="og:url"                content="www.thebirdingbook.com/about/" />
<meta property="og:type"               content="website" />
<meta property="og:title"              content="The Birding Book - About" />
<meta property="og:description"        content="Learn about The Birding Book by reviewing the FAQ, privacy policy, and terms of service." />
<meta property="og:image"              content="{{ preview_url }}" />

{% endblock %}

{% block content %}
<div class="page-content">
	<section class="mdl-grid">
		<div class="mdl-cell mdl-cell--4-col mdl-cell--1-offset-desktop">
			<section class="docs-toc docs-text-styling table-of-contents">
				<p><b>Contents</b></p>
				<nav class="section-content">
					<ul class="mdl-list">
						<li class="mdl-list__item">
							<span class="mdl-list__item-primary-content"><a href="#faq">Frequently Asked Questions</a></span>
						</li>
						<li class="mdl-list__item">
							<span class="mdl-list__item-primary-content"><a href="#tos">Terms of Service</a></span>
						</li>
						<li class="mdl-list__item">
							<span class="mdl-list__item-primary-content"><a href="#privacy-policy">Privacy Policy</a></span>
						</li>
					</ul>
				</nav>
			</section>
		</div>
		<div class="mdl-cell mdl-cell--10-col-desktop mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-cell--1-offset-desktop mdl-card">
			<div class="mdl-card__title" id="faq">
				<h2 class="mdl-card__title-text">What is The Birding Book?</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<ul class="mdl-list">
					<li class="mdl-list__item">
						<p>The Birding Book a new App for Birding.  Post your bird sightings and browse sightings from other members.  Birders can use the app to quickly review <b>which birds</b> have been seen, <b>where</b> and <b>when</b>.  Members can help each other confidently identify birds using the build in <b><a class="no-decoration" href="#species-suggestion">Species Suggestion Tool</a></b></p>
					</li>
				</ul>
			</div>
			<div class="mdl-card__title" id="how-to-post">
				<h2 class="mdl-card__title-text">How to post a sighting?</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<ul class="mdl-list">
					<li class="mdl-list__item">
						<p>Use the Main Menu ( top left of screen ) and select <a class="no-decoration" href="{% url 'birds:new_sighting' %}"><b>New Sighting</b></a>.  Fill out the few required information fields.  Add <b>as many pictures as you want</b> ( optional ).  Use the map to indicate where you saw the bird.</p>
					</li>
				</ul>
			</div>
			<div class="mdl-card__title" id="species-suggestion">
				<h2 class="mdl-card__title-text">Species Selection Tool</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<ul class="mdl-list">
					<li class="mdl-list__item">
						<p>When you see a bird that you know, use this tool to help a birder out, by <b>suggesting the right species</b>.  Other birders can vote, or "agree" which species they think is the correct one.</p>
					</li>
				</ul>
			</div>
			<div class="mdl-card__title" id="pictures-near-me">
				<h2 class="mdl-card__title-text">How do I view Bird Pictures near me?</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<ul class="mdl-list">
					<li class="mdl-list__item">
						<p>Use the location search tool.  Navigate to <b><a class="no-decoration" href="{% url 'birds:map' %}">The Birding Book Map</a></b> to see the birds by geographic location.</p>
					</li>
				</ul>
			</div>
		</div>
		<div class="mdl-cell mdl-cell--10-col-desktop mdl-cell--12-col-tablet mdl-cell--12-col-phone  mdl-cell--1-offset-desktop mdl-card mdl-shadow--3dp">
	
			<div class="mdl-card__title" id="tos">
				<h2 class="mdl-card__title-text">Terms of Service ("Terms")</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-components__warning">
					<b>Last updated:</b> 2/10/2017 <!--DATE UPDATE-->
				</div> 
				<br>
				<p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the http://www.TheBirdingBook.com website (the "Service") operated by The Birding Book ("us", "we", or "our").</p>
				<p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>
				<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with	any part of the terms then you may not access the Service.</p>
				<!--<div class="mdl-components__warning">Termination clause for websites that do not have accounts. If your website or mobile app allows users to register and have an account, create your own Terms of Service.</div>-->
				<br>
				<h5>User Contributed Content</h5>
				
				<p>
				User contributed content, except username info, should be considered public content. This includes all information pertaining to sightings, feedback, comments, avatar and other info. You're not required to enter personally identifiable information into The Birding Book website.
				</p>
				<p>
					All personally identifiable information is stored on the Google firebase servers.
				</p>
				
				<h5>User Authentication</h5>
				<p>
					The Birding Book utilizes <a href="https://en.wikipedia.org/wiki/Firebase">Google's Firebase API</a>. We use <a href="https://jwt.io/">JSON Web Tokens</a> to securely transfer authenication to The Birding Book website.
				</p>
				
				<h5>Termination</h5>
				<p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
				<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity	and limitations of liability.</p>
				<h5>Links To Other Web Sites</h5>
				<p>Our Service may contain links to third­party web sites or services that are not owned or controlled by The Birding Book.</p>
				<p>The Birding Book has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that The Birding Book shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
				<p>We strongly advise you to read the terms and conditions and privacy policies of any third­party web sites or services that you visit.</p>
				<h5>Governing Law</h5>
				<p>These Terms shall be governed and construed in accordance with the laws of United States of America, without regard to its conflict of law provisions.</p>
				<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
				<h5>Changes</h5>
				<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 (change this) days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
				<p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>
				<h5>Contact Us</h5>
				<p>If you have any questions about these Terms, please contact us, <a href="mailto:info@thebirdingbook.com?subject=Terms of Service Questions">info@thebirdingbook.com</a>.</p>
			</div>
		</div>	
		<div class="mdl-cell mdl-cell--10-col-desktop mdl-cell--12-col-tablet mdl-cell--12-col-phone  mdl-cell--1-offset-desktop mdl-card mdl-shadow--3dp">
			<div class="mdl-card__title" id="privacy-policy">
				<h2 class="mdl-card__title-text">Privacy Policy</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<div class="mdl-components__warning"><b>Last updated:</b> 2/10/2017 <!--DATE UPDATE--></div>
				<br>
				<p>TheBirdingBook.com ("us", "we", or "our") operates http://www.thebirdingbook.com (the "Site"). This page informs you of our policies regarding the collection, use and disclosure of Personal Information we receive from users of the Site.</p>
				<p>We use your Personal Information only for providing and improving the Site. By using the Site, you
				agree to the collection and use of information in accordance with this policy.<p>
				<h5>Information Collection And Use</h5>
				<p>While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to your name ("Personal Information").</p>
				<h5>Log Data</h5>
				<p>Like many site operators, we collect information that your browser sends whenever you visit our Site
				("Log Data").</p>
				<p>This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those pages and other statistics.</p>
				
				<p>In addition, we may use third party services such as Google Analytics that collect, monitor and analyze this …</p>
				<!--<div class="mdl-components__warning">The Log Data section is for businesses that use analytics or tracking services in websites or apps, like Google Analytics. For the full disclosure section, create your own Privacy Policy.</div>-->
				<br>
				<h5>Communications</h5>
				<p>We may use your Personal Information to contact you with newsletters, marketing or promotional
				materials and other information that ...
				The Communications section is for businesses that may contact users via email (email
				newsletters) or other methods. For the full disclosure section, create your own Privacy Policy.
				<h5>Cookies</h5>
				<p>Cookies are files with small amount of data, which may include an anonymous unique identifier.  Cookies are sent to your browser from a web site and stored on your computer's hard drive.</p>
				<p>Like many sites, we use "cookies" to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Site.</p>
				<h5>Security</h5>
				<p>The security of your Personal Information is important to us, but remember that no method of	transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>
				<h5>Changes To This Privacy Policy</h5>
				<p>This Privacy Policy is effective as of 9/9/2016<!--DATE UPDATE--> and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this
				page.</p>
				<p>We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</p>
				<p>If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us, or by placing a prominent notice on our website.</p>
				<h5>Contact Us</h5>
				<p>If you have any questions about this Privacy Policy, please contact us, 
				<a href="mailto:info@thebirdingbook.com?subject=Privacy Policy Questions">info@thebirdingbook.com</a>.</p>
			</div>
		</div>
	</section>
</div>
{% endblock %}

birds/templates/birds/comments.html
{% for comment in comments %}
	<div class="mdl-card__supporting-text">
		<a href="{% url 'birds:user' comment.user.id %}"><b>{{ comment.user }}</b></a>: {{ comment.comment }}
	</div>
{% endfor %}

birds/templates/birds/feedback.html
{% extends 'birds/base.html' %}


{% block desc_title %}
<title>The Birding Book - Feedback</title>
<meta name="description" content="Please leave us feedback to let us know how we can make The Birding Book work better for you.">

<meta property="og:url"                content="www.thebirdingbook.com/feedback/" />
<meta property="og:type"               content="website" />
<meta property="og:title"              content="The Birding Book - Feedback" />
<meta property="og:description"        content="Please leave us feedback to let us know how we can make The Birding Book work better for you." />
<meta property="og:image"              content="{{ preview_url }}" />

{% endblock %}

{% block content %}

<div class="mdl-cell mdl-cell--8-col mdl-cell--1-offset-desktop">
	<form action="{% url 'birds:feedback' %}" method="POST">{% csrf_token %}
	{% if thanks %}

		<div class="mdl-card__title">
			<h3 class="mdl-card__title-text">Thank You, we'll get back to you shortly.</h3>
		</div>

	{% else %}


		<div class="mdl-card__title">
			
				<div class="mdl-textfield mdl-js-textfield">
					<textarea class="mdl-textfield__input" type="text" rows= "3" id="feedback_text_id" name="feedback_text" ></textarea>
					<label class="mdl-textfield__label" for="feedback_text_id">Let us know what you think...</label>
				</div>
			
		</div>


		<div class="mdl-card__supporting-text">
			What would you like to see in the Birding Book?  How can we make the experience better? Problems?  Issues?
		</div>

		<div class="mdl-card__actions mdl-card--border">
			<button class="mdl-button mdl-js-button mdl-button--primary">
				Send Message
			</button>
		</div>

	{% endif %}
	</form>
</div>



{% endblock %}